[simulation]
boxLength = 20
exitWidth = 1.2
pedestrians = 400
minRadius = 0.1
maxRadius = 0.37
beta = 0.9
vdMax = 2.0
outputInterval = 5
amountDoors = 2

[benchmarks]
exitWidths = [ 3.0, 2.4, 1.8, 1.2,]
pedestrians = [ 380, 320, 260, 200,]

[files]
staticInput = "./static.txt"
output = "./out/output.txt"
benchmark = "./out/benchmark.txt"
